### ISSUE TITLE
出错了

### ISSUE THREAD

**Issue by cdonsun** [aliyun/openapi-core-ruby-sdk#17]
activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- ./rpc_client.rb (LoadError)

**Comment by songshenzong** [comment]
> activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- ./rpc_client.rb (LoadError)

已收到，我们会轻快处理。

**Comment by bill1997603** [comment]
这个问题解决了吗

**Comment by i-free-developer** [comment]
gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require': cannot load such file -- ./rpc_client.rb (LoadError)

还是没有解决吗
